import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import coursesRouter from "./courses";
import enrollmentsRouter from "./enrollments";
import modulesRouter from "./modules";
import quizzesRouter from "./quizzes";
import questionsRouter from "./questions";
import submissionsRouter from "./submissions";
import gradesRouter from "./grades";
import alertsRouter from "./alerts";
import announcementsRouter from "./announcements";
import fileSubmissionsRouter from "./file-submissions";
import submissionSlotsRouter from "./submission-slots";
import invitationsRouter from "./invitations";
import aiRouter from "./ai";
import aiAgentRouter from "./ai-agent";
import assignmentsRouter from "./assignments";
import discussionsRouter from "./discussions";
import messagesRouter from "./messages";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(coursesRouter);
router.use(enrollmentsRouter);
router.use(modulesRouter);
router.use(quizzesRouter);
router.use(questionsRouter);
router.use(submissionsRouter);
router.use(gradesRouter);
router.use(alertsRouter);
router.use(announcementsRouter);
router.use(fileSubmissionsRouter);
router.use(submissionSlotsRouter);
router.use(invitationsRouter);
router.use(aiRouter);
router.use(aiAgentRouter);
router.use(assignmentsRouter);
router.use(discussionsRouter);
router.use(messagesRouter);

export default router;
